# Información del proyecto
sonar.projectKey=inscripciones_incad_5
sonar.projectName=Inscripciones INCAD Ver 5
sonar.projectVersion=5.0

# Directorios a analizar
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclusiones (ajusta según tu estructura)
sonar.exclusions=**/vendor/**,**/node_modules/**,**/tests/**,**/*.js,**/*.css

# Lenguaje
sonar.language=php

# Coverage (si tienes reportes de cobertura)

# sonar.php.coverage.reportPaths=coverage.xml
